# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: gokart

---
# Deployment for Django App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: gokart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: public.ecr.aws/w0n7y4q3/backend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
# Service for Django App
apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: gokart
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000


---
#ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: gokart
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: gocart.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-app
            port:
              number: 8000
